"""
User model helpers

MongoDB doesn't require explicit models, but this file documents
the user collection schema and provides helper functions.
"""

from typing import Dict, Any
from datetime import datetime


USER_SCHEMA = {
    "_id": "ObjectId",  # Auto-generated by MongoDB
    "email": "string (unique)",
    "google_id": "string (unique, optional)",
    "name": "string",
    "picture": "string (optional)",
    "role": "string (default: 'user')",
    "created_at": "datetime",
    "last_login": "datetime"
}


# Indexes are created in app/db.py ensure_indexes()
# - email (unique)
# - google_id (unique, sparse)
